<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Game_Control</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaveLibraryTestUI\CaveLibraryTestUI.csproj" />
    <ProjectReference Include="..\CaveLibrary\CaveLibrary.csproj" />
    <ProjectReference Include="..\GameLocationLibrary\GameLocationLibrary.csproj" />
    <ProjectReference Include="..\PlayerLibrary\PlayerLibrary.csproj" />
    <ProjectReference Include="..\ScoreBoard\ScoreBoard.csproj" />
    <ProjectReference Include="..\SoundLibrary\SoundLibrary.csproj" />
    <ProjectReference Include="..\Trivia\Trivia.csproj" />
    <ProjectReference Include="..\UI Library\UI Library.csproj" />
  </ItemGroup>

</Project>
