<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Game_Control</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaveManager\Cave.csproj" />
    <ProjectReference Include="..\GameLocationLibrary\GameLocationLibrary.csproj" />
    <ProjectReference Include="..\PlayerLibrary\PlayerLibrary.csproj" />
    <ProjectReference Include="..\Player\Player.csproj" />
    <ProjectReference Include="..\ScoreBoardLibrary\ScoreBoardLibrary.csproj" />
    <ProjectReference Include="..\UI Library\UI Library.csproj" />
  </ItemGroup>

</Project>
