<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaveLibrary\CaveLibrary.csproj" />
    <ProjectReference Include="..\PlayerLibrary\PlayerLibrary.csproj" />
  </ItemGroup>

</Project>
