<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Hunt_the_Wumpus_2025</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="adjacentRooms.csv" />
    <None Remove="caveA-validDirections.csv" />
    <None Remove="caveB-validDirections.csv" />
    <None Remove="caveC-validDirections.csv" />
    <None Remove="caveD-validDirections.csv" />
    <None Remove="caveE-validDirections.csv" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="adjacentRooms.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="caveA-validDirections.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="caveB-validDirections.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="caveC-validDirections.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="caveD-validDirections.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="caveE-validDirections.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaveLibrary\CaveLibrary.csproj" />
    <ProjectReference Include="..\Game Control\Game Control.csproj" />
    <ProjectReference Include="..\PlayerLibrary\PlayerLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TriviaQuestions.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>