<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Hunt_the_Wumpus_2025</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\2030638_Choy_CaveTestUI\CaveTestUI.csproj" />
    <ProjectReference Include="..\CaveManager\Cave.csproj" />
    <ProjectReference Include="..\Game Control\Game Control.csproj" />
    <ProjectReference Include="..\GameLocationLibrary\GameLocationLibrary.csproj" />
    <ProjectReference Include="..\ScoreBoardLibrary\ScoreBoardLibrary.csproj" />
    <ProjectReference Include="..\UI Library\UI Library.csproj" />
  </ItemGroup>

</Project>